version: '3'

services:
  app:
    build: .
    container_name: phone-locator-bot
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://phonelocator:phonelocator@cluster0.i9c1x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 